import "@radix-ui/themes/styles.css";
import './theme-config.css';
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter  } from "next/font/google";
import { Container, Theme } from "@radix-ui/themes";


import NavBar from "./NavBar";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <Theme accentColor="violet" radius="full" appearance="dark">
          <NavBar />
          <main className="px-3 py-2.5">
            <Container>
              {children}
            </Container>
          </main>
        </Theme>
      </body>
    </html>
  );
}
